# Generated by Django 5.0.4 on 2024-04-30 07:22

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
