# Generated by Django 5.0.4 on 2024-04-30 08:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=4326),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
    ]
