# Generated by Django 5.0.4 on 2024-04-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_institution_geom_alter_institution_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Països'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Institució', 'verbose_name_plural': 'Institucions'},
        ),
    ]
