# Generated by Django 5.0.4 on 2024-05-02 08:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0008_country_bbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=4326, verbose_name='Localització'),
        ),
    ]
