# Generated by Django 5.0.4 on 2024-05-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0010_country_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='iso2',
        ),
    ]
