# Generated by Django 5.0.4 on 2024-05-03 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0013_remove_institution_mobility_mobility_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='mobility_calendar',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='mobility_result',
        ),
        migrations.AddField(
            model_name='mobilitycalendar',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.institution', verbose_name='Institució'),
        ),
        migrations.AddField(
            model_name='mobilitydone',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.institution', verbose_name='Institució'),
        ),
    ]
