# Generated by Django 5.0.4 on 2024-05-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0014_remove_institution_mobility_calendar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilitycalendar',
            old_name='yeaar',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='mobilitydone',
            old_name='yeaar',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='institution',
            name='region_udg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Regió segons UdG'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='region_ue',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Resgió segons UE'),
        ),
        migrations.AlterField(
            model_name='mobility',
            name='staying_time_units',
            field=models.CharField(choices=[('days', 'Dies'), ('months', 'Mesos'), ('years', 'Anys')], default='days', max_length=9, verbose_name="Tipus d 'estada"),
        ),
        migrations.AlterField(
            model_name='mobility',
            name='staying_units',
            field=models.IntegerField(default=1, verbose_name='Número de dies / mesos / anys'),
        ),
        migrations.AlterField(
            model_name='mobilitycalendar',
            name='units',
            field=models.IntegerField(verbose_name='Número de persones'),
        ),
    ]
