# Generated by Django 5.0.4 on 2024-05-07 06:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso3', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, spatial_index=False, srid=4326)),
                ('bbox', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Països',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Perfil de mobilitat',
                'verbose_name_plural': 'Perfils de mobilitats',
            },
        ),
        migrations.CreateModel(
            name='YearResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('description', models.CharField(max_length=255, verbose_name='Descripció')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('oi', models.CharField(blank=True, max_length=25)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_ue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regió segons UE')),
                ('region_udg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regió segons UdG')),
                ('benefits', models.TextField(blank=True, null=True, verbose_name='Beneficis previstos de la col·laboració per a la UdG i per a la contrapart. Alinieació amb les polítiques de l’UE ')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=4326, verbose_name='Localització')),
                ('empowerment', models.TextField(blank=True, null=True, verbose_name='Fortaleses de la institució per a la UdG i viceversa')),
                ('collaboration_start', models.TextField(blank=True, null=True, verbose_name='Inici de la col·laboració')),
                ('motive', models.TextField(blank=True, null=True, verbose_name='Fortaleses de la institució per a la UdG i viceversa')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.country', verbose_name='País')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institució',
                'verbose_name_plural': 'Institucions',
            },
        ),
        migrations.CreateModel(
            name='MobilityDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Any')),
                ('in_or_out', models.CharField(choices=[('in', 'in'), ('out', 'out')], default='out', max_length=9, verbose_name='In/Out')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripció')),
                ('program', models.CharField(blank=True, max_length=255, null=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobility.institution', verbose_name='Institució')),
            ],
            options={
                'verbose_name': 'Mobilitat realizada',
                'verbose_name_plural': 'Mobilitats realizades',
            },
        ),
        migrations.CreateModel(
            name='MobilityCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Any')),
                ('units', models.IntegerField(verbose_name='Número de persones')),
                ('in_or_out', models.CharField(choices=[('in', 'in'), ('out', 'out')], default='out', max_length=9, verbose_name='In/Out')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobility.institution', verbose_name='Institució')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.person', verbose_name='Tipus de mobilitat')),
            ],
            options={
                'verbose_name': 'Calendarització de les mobilitats',
                'verbose_name_plural': 'Calendaritzacions de les mobilitats',
            },
        ),
        migrations.CreateModel(
            name='Mobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_or_out', models.CharField(choices=[('in', 'in'), ('out', 'out')], default='out', max_length=9, verbose_name='In/Out')),
                ('staying_time_units', models.CharField(choices=[('days', 'Dies'), ('months', 'Mesos'), ('years', 'Anys')], default='days', max_length=9, verbose_name="Tipus d 'estada")),
                ('staying_units', models.IntegerField(default=1, verbose_name='Número de dies / mesos / anys')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobility.institution', verbose_name='Institució')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.person', verbose_name='Tipus de mobilitat')),
            ],
            options={
                'verbose_name': 'Mobilitats',
                'verbose_name_plural': 'Mobilitats',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripció')),
                ('year_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.yearresult', verbose_name='Resultats')),
            ],
            options={
                'verbose_name': 'Resultats obtinguts',
                'verbose_name_plural': 'Resultats obtinguts',
            },
        ),
    ]
